In [1]:
import pandas as pd
import numpy as np
import data_preprocessing as dp
import mdp
import Replay_Buffer
import torch as T

### load training data

In [2]:
# load data: DR_USA_Roundabout_FT_train.csv

# Roundabout data google drive path: "https://drive.google.com/file/d/1Ls92QosBDIyoDcEudSVGukP68pw1FRXW/view?usp=sharing"
# please download it to your local computer

url_FT_train = 'INTERACTION/DR_USA_Roundabout_FT_train.csv'
df_train = pd.read_csv(url_FT_train)

# look at the top 30 rows of data
df_train.head(30)

case_id  track_id  frame_id  timestamp_ms          agent_type         x  \
0       1.0         1         1           100  pedestrian/bicycle  1044.509   
1       1.0         2         1           100  pedestrian/bicycle  1043.840   
2       1.0         3         1           100  pedestrian/bicycle  1007.638   
3       1.0         4         1           100                 car  1036.888   
4       1.0         5         1           100                 car  1038.206   
5       1.0         6         1           100                 car  1004.449   
6       1.0         7         1           100                 car  1013.407   
7       1.0         8         1           100                 car  1048.917   
8       1.0         9         1           100                 car   993.728   
9       1.0        10         1           100                 car   981.026   
10      1.0        11         1           100                 car  1055.975   
11      1.0        12         1           100                 car  1036.398   
12      1.0        13         1           100                 car   965.730   
13      1.0         1         2           200  pedestrian/bicycle  1044.520   
14      1.0         2         2           200  pedestrian/bicycle  1043.833   
15      1.0         3         2           200  pedestrian/bicycle  1007.705   
16      1.0         4         2           200                 car  1036.793   
17      1.0         5         2           200                 car  1037.975   
18      1.0         6         2           200                 car  1004.630   
19      1.0         7         2           200                 car  1013.891   
20      1.0         8         2           200                 car  1048.827   
21      1.0         9         2           200                 car   993.847   
22      1.0        10         2           200                 car   981.467   
23      1.0        11         2           200                 car  1055.864   
24      1.0        12         2           200                 car  1036.404   
25      1.0        13         2           200                 car   966.251   
26      1.0         1         3           300  pedestrian/bicycle  1044.533   
27      1.0         2         3           300  pedestrian/bicycle  1043.833   
28      1.0         3         3           300  pedestrian/bicycle  1007.770   
29      1.0         4         3           300                 car  1036.699   

           y     vx     vy  psi_rad  length  width  
0   1012.175  0.103 -1.005      NaN     NaN    NaN  
1   1013.348 -0.101 -1.362      NaN     NaN    NaN  
2   1022.038  0.687  0.787      NaN     NaN    NaN  
3    976.415 -1.063  1.980    2.064    5.20   1.86  
4    993.477 -2.343  5.161    1.997    4.68   1.90  
5    984.315  1.823 -0.369   -0.200    4.93   1.97  
6    987.769  4.564 -3.386   -0.638    4.83   1.93  
7    980.407 -0.894  0.591    2.557    5.13   1.96  
8    985.780  1.184  0.012    0.010    4.54   1.81  
9    985.788  4.411  0.197    0.045    4.55   1.78  
10   975.473 -1.121  0.764    2.543    4.74   1.86  
11  1022.086 -0.089 -0.115   -2.233    4.39   1.83  
12   984.556  5.207  0.307    0.059    4.34   1.75  
13  1012.075  0.116 -1.000      NaN     NaN    NaN  
14  1013.212 -0.035 -1.356      NaN     NaN    NaN  
15  1022.113  0.653  0.706      NaN     NaN    NaN  
16   976.619 -1.047  1.985    2.056    5.20   1.86  
17   993.996 -2.341  5.201    1.994    4.68   1.90  
18   984.274  1.977 -0.404   -0.202    4.93   1.97  
19   987.467  4.561 -3.174   -0.608    4.83   1.93  
20   980.465 -0.920  0.608    2.558    5.13   1.96  
21   985.780  1.116  0.010    0.009    4.54   1.81  
22   985.805  4.259  0.182    0.043    4.55   1.78  
23   975.551 -1.130  0.773    2.542    4.74   1.86  
24  1022.098  0.000  0.000   -2.234    4.39   1.83  
25   984.588  5.170  0.307    0.059    4.34   1.75  
26  1011.974  0.139 -1.012      NaN     NaN    NaN  
27  1013.078  0.029 -1.341      NaN     NaN    NaN  
28  1022.180  0.6

### 1. create unique_id
### 2. change length, width and psi_rad from NaN to 0 for pedestrain/bicycle
### 3. change agent type to number for state vector (pedestrian/bicycle = -1; car = 1)

In [3]:
# add a new label unique_id using case_id and track_id
df_train['unique_id'] = df_train['case_id'].astype(int) * 100+ df_train['track_id']

# change length, width and psi_rad from NaN to 0 for pedestrain/bicycle
df_train.loc[df_train['agent_type'] == 'pedestrian/bicycle', 'length'] = 0
df_train.loc[df_train['agent_type'] == 'pedestrian/bicycle', 'width'] = 0
df_train.loc[df_train['agent_type'] == 'pedestrian/bicycle', 'psi_rad'] = 0


### important!!!
# agent_type pedestrain/bicycle = -1
# agent_type car = 1
df_train.loc[df_train['agent_type'] == 'pedestrian/bicycle', 'agent_type'] = -1
df_train.loc[df_train['agent_type'] == 'car', 'agent_type'] = 1
df_train

case_id  track_id  frame_id  timestamp_ms agent_type         x  \
0            1.0         1         1           100         -1  1044.509   
1            1.0         2         1           100         -1  1043.840   
2            1.0         3         1           100         -1  1007.638   
3            1.0         4         1           100          1  1036.888   
4            1.0         5         1           100          1  1038.206   
...          ...       ...       ...           ...        ...       ...   
4243282   9811.0         8        40          4000          1  1022.107   
4243283   9811.0         9        40          4000          1   996.468   
4243284   9811.0        10        40          4000          1  1019.894   
4243285   9811.0        11        40          4000          1  1028.592   
4243286   9811.0        12        40          4000          1   962.446   

                y     vx     vy  psi_rad  length  width  unique_id  
0        1012.175  0.103 -1.005    0.000    0.00   0.00        101  
1        1013.348 -0.101 -1.362    0.000    0.00   0.00        102  
2        1022.038  0.687  0.787    0.000    0.00   0.00        103  
3         976.415 -1.063  1.980    2.064    5.20   1.86        104  
4         993.477 -2.343  5.161    1.997    4.68   1.90        105  
...           ...    ...    ...      ...     ...    ...        ...  
4243282   985.137  7.470  1.627    0.215    4.19   1.87     981108  
4243283   986.201  7.374 -0.178   -0.024    4.64   1.90     981109  
4243284  1009.985 -7.780 -0.610   -3.063    4.72   1.87     981110  
4243285  1022.465 -1.619 -1.729   -2.324    4.49   1.83     981111  
4243286   984.626  8.161  0.351    0.043    5.56   2.04     981112  

[4243287 rows x 13 columns]

### use 10 cases (case1 to case10) for demonstrating and testing

In [4]:
# use case 1 to case 100 as a toy test dataframe
number_of_cases = 9800

df_train_small = df_train[df_train['case_id'] <= number_of_cases]
df_train_small 

case_id  track_id  frame_id  timestamp_ms agent_type         x  \
0            1.0         1         1           100         -1  1044.509   
1            1.0         2         1           100         -1  1043.840   
2            1.0         3         1           100         -1  1007.638   
3            1.0         4         1           100          1  1036.888   
4            1.0         5         1           100          1  1038.206   
...          ...       ...       ...           ...        ...       ...   
4238389   9800.0        14        40          4000          1   987.754   
4238390   9800.0        15        40          4000          1  1055.598   
4238391   9800.0        16        40          4000          1  1040.531   
4238392   9800.0        17        40          4000          1   973.104   
4238393   9800.0        18        40          4000          1  1042.338   

                y     vx     vy  psi_rad  length  width  unique_id  
0        1012.175  0.103 -1.005    0.000    0.00   0.00        101  
1        1013.348 -0.101 -1.362    0.000    0.00   0.00        102  
2        1022.038  0.687  0.787    0.000    0.00   0.00        103  
3         976.415 -1.063  1.980    2.064    5.20   1.86        104  
4         993.477 -2.343  5.161    1.997    4.68   1.90        105  
...           ...    ...    ...      ...     ...    ...        ...  
4238389   985.433  5.449  0.071    0.013    5.24   2.00     980014  
4238390   976.196 -1.233  0.867    2.529    4.33   1.81     980015  
4238391   969.451  0.000  0.000    2.100    5.02   2.06     980016  
4238392   985.236  4.229  0.202    0.048    4.54   1.89     980017  
4238393   986.348 -0.334  0.377    2.296    4.89   1.95     980018  

[4238394 rows x 13 columns]

In [5]:
print('--df--')
print('Total number of cases: ', df_train['case_id'].nunique())
print('Total number of agents: ', df_train.unique_id.nunique())
print('--df_small--')
print('Total number of cases: ', df_train_small['case_id'].nunique())
print('Total number of agents: ', df_train_small.unique_id.nunique())

--df--
Total number of cases:  9811
Total number of agents:  129019
--df_small--
Total number of cases:  9800
Total number of agents:  128872


### create uniqueTracks (a dictionary strore every unique agents (car, bike, or pedestrain)

In [6]:
# load uniqueTracks data
# uniqueTracks is a dictionary strore each unique object
uniqueTracks = dp.read_uniqueTracks(df_train_small)
uniqueTracks

{101: <data_preprocessing.uniqueTrack at 0x2834f3250>,
 102: <data_preprocessing.uniqueTrack at 0x282a6ea50>,
 103: <data_preprocessing.uniqueTrack at 0x283458a10>,
 104: <data_preprocessing.uniqueTrack at 0x28276d7d0>,
 105: <data_preprocessing.uniqueTrack at 0x28276ddd0>,
 106: <data_preprocessing.uniqueTrack at 0x106030110>,
 107: <data_preprocessing.uniqueTrack at 0x2834f2110>,
 108: <data_preprocessing.uniqueTrack at 0x282a84c90>,
 109: <data_preprocessing.uniqueTrack at 0x2834f0d50>,
 110: <data_preprocessing.uniqueTrack at 0x2834f3f90>,
 111: <data_preprocessing.uniqueTrack at 0x2834f2990>,
 112: <data_preprocessing.uniqueTrack at 0x2834f2410>,
 113: <data_preprocessing.uniqueTrack at 0x2834f0a50>,
 114: <data_preprocessing.uniqueTrack at 0x2834e1b10>,
 115: <data_preprocessing.uniqueTrack at 0x2834fbf50>,
 201: <data_preprocessing.uniqueTrack at 0x308743f50>,
 202: <data_preprocessing.uniqueTrack at 0x2834e0f50>,
 203: <data_preprocessing.uniqueTrack at 0x2834fbf90>,
 204: <dat

### information stored in the object

In [7]:
v_max = max(df_train_small['vx']**2 + df_train_small['vy']**2) ** 0.5

In [8]:
#Set Device
device = T.device('cuda:0' if T.cuda.is_available() else 'cpu')

In [12]:
#Initialize the buffer
replay_buffer = Replay_Buffer.ReplayBuffer(37, 2, device, 500000)

In [13]:
%%time
i=0
for unique_id,group in df_train_small.groupby('unique_id'):
    timestamps = group['timestamp_ms'].unique()
    num_timestamps = len(timestamps)
    for timestamp in timestamps[:num_timestamps - 1]:
        frame = group[group['timestamp_ms'] == timestamp]
        ego_id = unique_id
        _, interactive_agents = mdp.get_other_agents_unique_id(ego_id, timestamp, uniqueTracks)
        mdp_tuple = mdp.get_mdp_tuple(ego_id, interactive_agents, timestamp, uniqueTracks, v_max)
        if not not mdp_tuple:
            s, a, r, s_next, the_last_episode = mdp_tuple
            if the_last_episode == False:
                the_last_episode = 0
            else:
                the_last_episode = 1
            replay_buffer.add(s, a, s_next, r, the_last_episode)
            i=i+1

non_car_collision:  74201
non_car_collision:  74201
non_car_collision:  77701
non_car_collision:  77701
non_car_collision:  81001
non_car_collision:  81001
non_car_collision:  85601
non_car_collision:  85601
Unexpected exception formatting exception. Falling back to standard exception


Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/IPython/core/magics/execution.py", line 1340, in time
    exec(code, glob, local_ns)
  File "<timed exec>", line 9, in <module>
  File "/Users/shitanshubhushan/Documents/EECS-545-final-project/mdp.py", line 61, in get_mdp_tuple
    _, interactive_agents_next = get_other_agents_unique_id(ego_id, next_time, uniqueTracks)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shitanshubhushan/Documents/EECS-545-final-project/mdp.py", line -1, in get_other_agents_unique_id
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 2120, in showtraceback
    stb = self.InteractiveTB.structured_traceback(
          ^^^^^^^^^^^^^^^

In [14]:
i

509910

In [15]:
#Save the Buffer
replay_buffer.save("buffers/DR_USA_Roundabout_FT")

In [16]:
#Load the Buffer
replay_buffer_load = Replay_Buffer.ReplayBuffer(37, 2, device, 100000)
replay_buffer_load.load(f"buffers/DR_USA_Roundabout_FT")

In [17]:
replay_buffer_load.sample(1)

(tensor([[ 5.7020e+03,  5.7080e+03,  5.7050e+03,  5.7090e+03,  1.0326e+03,
           1.0007e+03,  8.3000e-02,  1.9300e-01,  1.1650e+00,  4.7600e+00,
           1.8100e+00,  1.0327e+03,  1.0009e+03,  1.0000e+00,  1.0402e+03,
           1.0079e+03,  0.0000e+00,  0.0000e+00,  3.0110e+00,  4.7600e+00,
           1.8300e+00,  1.0000e+00,  1.0351e+03,  9.8188e+02, -1.4570e+00,
           5.4650e+00,  1.8310e+00,  4.7600e+00,  1.8700e+00,  1.0000e+00,
           1.0271e+03,  1.0226e+03, -2.7670e+00, -2.2940e+00, -2.4490e+00,
           4.8100e+00,  2.0000e+00]]),
 tensor([[0.0640, 0.1500]]),
 tensor([[ 5.7020e+03,  5.7080e+03,  5.7050e+03,  5.7090e+03,  1.0326e+03,
           1.0007e+03,  6.4000e-02,  1.5000e-01,  1.1660e+00,  4.7600e+00,
           1.8100e+00,  1.0327e+03,  1.0009e+03,  1.0000e+00,  1.0402e+03,
           1.0079e+03,  0.0000e+00,  0.0000e+00,  3.0110e+00,  4.7600e+00,
           1.8300e+00,  1.0000e+00,  1.0350e+03,  9.8243e+02, -1.3400e+00,
           5.6010e+00,  1.8060e+